[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "0x10100E"
foreground = "0xC6C6C4"

[debug]
log_level = "Off"

[font]
builtin_box_drawing = true
size = 13.0

[font.glyph_offset]
y = 1

[font.normal]
family = "JetBrains Mono Nerd Font"

[font.offset]
y = 4

[mouse]
hide_when_typing = false

[scrolling]
history = 100000

[window]
blur = true
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 170
lines = 34
